const userNeed = [
  {
    name: "Pintar casa",
    description: "Pintar la casa completa",
    status: "in offer",
    location: "Buenos Aires, Argentina",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://rodapin.com/wp-content/uploads/2021/05/pintar-las-paredes-de-tu-casa.jpeg",
    userId: 51,
  },
  {
    name: "Pintar casa",
    description: "Pintar la casa completa",
    status: "in offer",
    location: "Buenos Aires, Argentina",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://rodapin.com/wp-content/uploads/2021/05/pintar-las-paredes-de-tu-casa.jpeg",
    userId: 65,
  },
  {
    name: "Contacto de luz",
    description: "Cambiar apagador de foco",
    status: "in progress",
    location: "Cancún, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo: "https://i.ytimg.com/vi/2GdnaMIaYGY/hqdefault.jpg",
    userId: 78,
  },
  {
    name: "Contacto de luz",
    description: "Cambiar apagador de foco",
    status: "in progress",
    location: "Cancún, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo: "https://i.ytimg.com/vi/2GdnaMIaYGY/hqdefault.jpg",
    userId: 79,
  },
  {
    name: "Contacto de luz",
    description: "Cambiar apagador de foco",
    status: "in progress",
    location: "Cancún, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo: "https://i.ytimg.com/vi/2GdnaMIaYGY/hqdefault.jpg",
    userId: 80,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 90,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 61,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 60,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 77,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 78,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 79,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 98,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 56,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 57,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 89,
  },
  {
    name: "Puertas de closet",
    description: "Reparar y barnizar puertas de closet de madera.",
    status: "in offer",
    location: "Tapachula, México",
    price: 1200,
    duration: 60,
    guarantee_time: 15,
    photo:
      "https://i.pinimg.com/originals/55/d0/b2/55d0b2d372b48b2f205979a88bfb23e3.jpg",
    userId: 52,
  },
];

const needMap = userNeed.map((el) => {
  return {
    name: el.name,
    description: el.description,
    status: el.status,
    location: el.location,
    photo: el.photo,
    price: el.price,
    duration: el.duration,
    guarantee_time: el.guarantee_time,
    UserId: el.userId,
  };
});

module.exports = { needMap };
