const professionals = [
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 4,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    userId: 2,
    profession: [
      {
        id: 2,
        name: "carpintero",
        ClientNeedId: null,
        Profession_Professional: {
          ProfessionalId: 2,
          ProfessionId: 2,
        },
      },
    ],
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 14,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 24,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 34,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 44,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 74,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 84,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 94,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 104,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 114,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 124,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 134,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 144,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 154,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 164,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 174,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 184,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 194,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 204,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 214,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 224,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 234,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 244,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 254,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 264,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 274,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 284,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 294,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 304,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 314,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 324,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 334,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 344,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 354,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 364,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 374,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 384,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 394,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 404,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 414,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 424,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 434,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 444,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 454,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 464,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "vip",
    profession: "carpintero",
    userId: 474,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 484,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 494,
  },
  {
    certification_name: "lalala",
    certification_img: "lalala",
    status: "normal",
    profession: "carpintero",
    userId: 504,
  },
];

const professionalMap = professionals.map((el) => {
  return {
    certification_name: el.certification_name,
    certification_img: el.certification_img,
    status: el.status,
    UserId: el.userId,
  };
});

module.exports = { professionalMap };
